### ISSUE TITLE
Getting Captcha Errors

### ISSUE THREAD

**Issue by Jake22262** [YABOIpy/Go-Raider#2]
![image](https://user-images.githubusercontent.com/106946536/209492948-343a1cc3-1c73-4892-9351-031e42b91845.png)

**Comment by Jake22262** [comment]
![image](https://user-images.githubusercontent.com/106946536/209494290-2fc6e024-70b8-44d3-a678-85847dd93546.png)
also getting this on the raid program.

**Comment by YABOIpy** [comment]
Ur tokens are getting captchas on join try the mass dm joiner it works fine for good tokens ill add captcha support soon
